# This workflow is designed for repositories utilizing trunk check for Terraform.
#   It runs trunk check to validate code quality and enforce standards in pull requests.
#   The workflow will fail if any violations are detected in the codebase.

name: Trunk Check
on:
  workflow_call:

jobs:
  trunk-check:
    name: Check for trunk check issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
